name: publish-to-npm

on:
  push:
    tags:
      - '*.*.*'

jobs:
  trufflehog:
    uses: ./.github/workflows/trufflehog.yml
  build-and-publish:
    needs:
      - trufflehog
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: 'lts/*'
      - run: npm ci
      - run: npm run prod
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
